---
title: "Advent of code - Day 5"
output: html_notebook
---
https://adventofcode.com/2020/day/5
```{r}
library(stringr)

compute_row = function(boarding_pass){
  min_row = 0
  max_row = 127
  for(letter in unlist(str_split(str_extract(boarding_pass, "^(F|B){7}"), ""))){
    if(letter == "F"){
      max_row = floor((max_row - min_row)/2) + min_row
    } else {
      min_row = ceiling((max_row - min_row)/2) + min_row
    }
  }
  return(min_row)
}

compute_col = function(boarding_pass){
  min_col = 0
  max_col = 7
  for(letter in unlist(str_split(str_extract(boarding_pass, "(R|L){3}$"), ""))){
    if(letter == "L"){
      max_col = floor((max_col - min_col)/2) + min_col
    } else {
      min_col = ceiling((max_col - min_col)/2) + min_col
    }
  }
  return(min_col)
}

data = data.frame(input = readLines("Input/day5.1.txt"))

data$row = sapply(data$input, compute_row)
data$col = sapply(data$input, compute_col)
data$id = data$row * 8 + data$col

max(data$id)
```

https://adventofcode.com/2020/day/5#part2

```{r}
possible = min(data$id):max(data$id)
possible[!possible %in% data$id]
```

